CSharpMVC_BuildingAndConferenceRoomAppAssignment/ViewModels/EnterBuildingInformationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CSharpMVC_BuildingAndConferenceRoomAppAssignment.ViewModels
{
    public class EnterBuildingInformationViewModel
    {
        [Required]
        [Display(Name = "Building ID")]
        public string BuildingId { get; set; }

        [Required]
        [Display(Name = "Building Name")]
        public string BuildingName { get; set; }

        [Required]
        [Display(Name = "Address")]
        public string StreetAddress { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string State { get; set; }
        [Required]
        public string Zip { get; set; }
        [Required]
        public string Country { get; set; }
        [Required]
        [Display(Name = "Phone Number")]
        public string MainBuildingPhoneNumber { get; set; }
        [Required]
        [Display(Name = "Floors")]
        public string NumberOfFloors { get; set; }
        [Required]
        [Display(Name = "Conference Rooms")]
        public string NumberOfConferenceRooms { get; set; }
        public bool EntrySuccessful { get; set; }
        public string Message { get; set; }
        public string Classification { get; set; }
        public string Type { get; set; }
    }
}

CSharpMVC_BuildingAndConferenceRoomAppAssignment/ViewModels/ViewBuildingInformationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CSharpMVC_BuildingAndConferenceRoomAppAssignment.ViewModels
{
    public class ViewBuildingInformationViewModel
    {
        [Display(Name = "Building ID")]
        public string BuildingId { get; set; }
        [Display(Name = "Building Name")]
        public string BuildingName { get; set; }
        [Display(Name = "Address")]
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        [Display(Name = "Phone Number")]
        public string MainBuildingPhoneNumber { get; set; }
        [Display(Name = "Floors")]
        public string NumberOfFloors { get; set; }
        [Display(Name = "Conference Rooms")]
        public string NumberOfConferenceRooms { get; set; }
    }
}

CSharpMVC_BuildingAndConferenceRoomAppAssignment/Controllers/BuildingInformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CSharpMVC_BuildingAndConferenceRoomAppAssignment.Models;
using CSharpMVC_BuildingAndConferenceRoomAppAssignment.ViewModels;
using CSharpMVC_BuildingAndConferenceRoomAppAssignment.BusinessLogic;

namespace CSharpMVC_BuildingAndConferenceRoomAppAssignment.Controllers
{
    public class BuildingInformationController : Controller
    {
        // GET: BuildingInformation
        public ActionResult ViewBuildingInformation()
        {
            //Load the building information from the database
            BuildingBL buildingBL = new BuildingBL();
            List<ViewBuildingInformationViewModel> buildingViewModels = buildingBL.GetAllBuildings();

            //Uncomment the line below to load dummy data
            //List<ViewBuildingInformationViewModel> buildingViewModels = buildingBL.LoadBuildingData();

            return View(buildingViewModels);
        }
        public ActionResult EnterBuildingInformation()
        {            
            return View();
        }

        [HttpPost]
        public ActionResult EnterBuildingInformation(EnterBuildingInformationViewModel building)
        {
            if (ModelState.IsValid)
            {
                //Determine building classification
                BuildingBL buildingBL = new BuildingBL();
                building.Classification = buildingBL.DetermineBuildingClassification(building);

                //Determine building type (tower or standard)
                building.Type = buildingBL.DetermineBuildingType(building);

                ModelState.Clear();
                EnterBuildingInformationViewModel buildingNew = new EnterBuildingInformationViewModel();
                buildingNew.EntrySuccessful = true;
                buildingNew.Message = $"Entry accepted for {building.BuildingName} located in city {building.City}.  " +
                    $"Building is classified as a {building.Classification}.  Building type is {building.Type}.";
                return View(buildingNew);
            }

            //Return the model as there's an error and the user needs to see
            // what has been entered.
            return View(building);
        }

        public ActionResult SaveBuildingDetail(EnterBuildingInformationViewModel building)
        {
            //Return the new building model instance in the View - This is how you'd go to a new page after adding (uncomment to just go to a new page after adding)
            /////return View(building);

            //Call Business Logic -> Repository -> etc. to save the data here

            //Add a success messsage to the ViewModel.
            building.EntrySuccessful = true;

            //Return to the EnterBuildingInformation View, passing the View Model
            return View("EnterBuildingInformation", building);
        }
    }
}

CSharpMVC_BuildingAndConferenceRoomAppAssignment/Views/BuildingInformation/EnterBuildingInformation.cshtml
@model CSharpMVC_BuildingAndConferenceRoomAppAssignment.ViewModels.EnterBuildingInformationViewModel

@{
    ViewBag.Title = "EnterBuildingInformation";
}

<h2>New Building Information</h2>


@using (Html.BeginForm("EnterBuildingInformation", "BuildingInformation", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Please enter the building details below.</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BuildingId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BuildingId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BuildingId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BuildingName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BuildingName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BuildingName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StreetAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreetAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreetAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MainBuildingPhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MainBuildingPhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MainBuildingPhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfFloors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfFloors, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfFloors, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfConferenceRooms, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfConferenceRooms, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfConferenceRooms, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" onclick="ClearMessage();" />
            </div>
        </div>

        <br />

        @{
            if (Model != null)
            {
                if (Model.EntrySuccessful)
                {
                    <h3 id="h3-message">@Model.Message</h3>
                    Model.EntrySuccessful = false;
                }
            }
        }
    </div>
}

<div>
    @Html.ActionLink("Main Menu", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        function ClearMessage() {
            const msg = document.getElementById('h3-message');
            msg.innerHTML = "";
        }
    </script>
}

CSharpMVC_BuildingAndConferenceRoomAppAssignment/Views/BuildingInformation/SaveBuildingDetail.cshtml
@{
    ViewBag.Title = "SaveBuildingDetail";
}

<h1>Success!</h1>

<h2>Building details successfully saved!</h2>

<div>
    @Html.ActionLink("Return to Building Entry Form", "EnterBuildingInformation", "BuildingInformation") <br />
    @Html.ActionLink("Main Menu", "Index", "Home")
</div>

CSharpMVC_BuildingAndConferenceRoomAppAssignment/Views/BuildingInformation/ViewBuildingInformation.cshtml
@model IEnumerable<CSharpMVC_BuildingAndConferenceRoomAppAssignment.ViewModels.ViewBuildingInformationViewModel>

@{
    ViewBag.Title = "ViewBuildingInformation";
}

<h2>Building Information</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BuildingId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BuildingName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StreetAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MainBuildingPhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfFloors)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfConferenceRooms)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BuildingId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BuildingName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StreetAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Zip)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MainBuildingPhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfFloors)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfConferenceRooms)
        </td>      
    </tr>
}
</table>

<div>
    @Html.ActionLink("Main Menu", "Index", "Home")
</div>