CSharpMVC_BuildingAndConferenceRoomAppAssignment/ViewModels/EnterConferenceRoomInformationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CSharpMVC_BuildingAndConferenceRoomAppAssignment.ViewModels
{
    public class EnterConferenceRoomInformationViewModel
    {
        [Required]
        [Display(Name = "Room ID")]
        public string RoomId { get; set; }
        [Required]
        [Display(Name = "Room Name")]
        public string RoomName { get; set; }
        [Required]
        [Display(Name = "Building")]
        public string RoomBuilding { get; set; }
        [Required]
        [Display(Name = "Phone Number")]
        public string RoomPhoneNumber { get; set; }       
        [Display(Name = "A/V Capable?")]
        public bool RoomIsAVCapable { get; set; }
        [Required]
        [Display(Name = "Capacity")]
        public string RoomCapacity { get; set; }
        public bool EntrySuccessful { get; set; }
        public string Message { get; set; }
        public string Size { get; set; }

    }
}

CSharpMVC_BuildingAndConferenceRoomAppAssignment/ViewModels/ViewConferenceRoomInformationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CSharpMVC_BuildingAndConferenceRoomAppAssignment.ViewModels
{
    public class ViewConferenceRoomInformationViewModel
    {
        [Display(Name = "Room ID")]
        public string RoomId { get; set; }
        [Display(Name = "Room Name")]
        public string RoomName { get; set; }
        [Display(Name = "Building")]
        public string RoomBuilding { get; set; }
        [Display(Name = "Phone Number")]
        public string RoomPhoneNumber { get; set; }
        [Display(Name = "A/V Capable?")]
        public bool RoomIsAVCapable { get; set; }
        [Display(Name = "Capacity")]
        public string RoomCapacity { get; set; }
    }
}

CSharpMVC_BuildingAndConferenceRoomAppAssignment/Controllers/ConferenceRoomInformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CSharpMVC_BuildingAndConferenceRoomAppAssignment.Models;
using CSharpMVC_BuildingAndConferenceRoomAppAssignment.ViewModels;
using CSharpMVC_BuildingAndConferenceRoomAppAssignment.BusinessLogic;

namespace CSharpMVC_BuildingAndConferenceRoomAppAssignment.Controllers
{
    public class ConferenceRoomInformationController : Controller
    {
        // GET: ConferenceRoomInformation
        public ActionResult ViewConferenceRoomInformation()
        {
            ConferenceRoomBL conferenceRoomBL = new ConferenceRoomBL();
            List<ViewConferenceRoomInformationViewModel> conferenceRooms = conferenceRoomBL.GetAllConferenceRooms();

            //Uncomment the line below to load dummy data
            //List<ViewConferenceRoomInformationViewModel> conferenceRooms = conferenceRoomBL.LoadConferenceRoomData();

            return View(conferenceRooms);
        }

        public ActionResult EnterConferenceRoomInformation()
        {        
            return View();
        }

        [HttpPost]
        public ActionResult EnterConferenceRoomInformation(EnterConferenceRoomInformationViewModel conferenceRoom)
        {
            if (ModelState.IsValid)
            {
                //Determine building size based on capacity
                ConferenceRoomBL conferenceRoomBL = new ConferenceRoomBL();
                conferenceRoom.Size = conferenceRoomBL.DetermineSize(conferenceRoom);
               
                ModelState.Clear();
                EnterConferenceRoomInformationViewModel conferenceRoomNew = new EnterConferenceRoomInformationViewModel();
                conferenceRoomNew.EntrySuccessful = true;
                conferenceRoomNew.Message = $"Entry accepted for {conferenceRoom.RoomName} located in building {conferenceRoom.RoomBuilding}.  " +
                    $"Conference room size is classifed as {conferenceRoom.Size}.";
                return View(conferenceRoomNew);
            }

            //Return the model as there's an error and the user needs to see
            // what has been entered.
            return View(conferenceRoom);
        }

        public ActionResult SaveConferenceRoomDetail(EnterConferenceRoomInformationViewModel conferenceRoom)
        {
            //Return the new conference room view model instance in the View - This is how you'd go to a new page after adding
            /////return View(conferenceRoom);
            ///
            //Write to the DB here

            EnterConferenceRoomInformationViewModel conferenceRoomNew = new EnterConferenceRoomInformationViewModel();
            conferenceRoomNew.EntrySuccessful = true;
            conferenceRoomNew.Message = $"Entry accepted for {conferenceRoom.RoomName} located in building {conferenceRoom.RoomBuilding}.";

            //Return to the Enter Conference Room Info View, passing the View Model
            return View("EnterConferenceRoomInformation", conferenceRoomNew);
        }
    }
}

CSharpMVC_BuildingAndConferenceRoomAppAssignment/Views/ConferenceRoomInformation/EnterConferenceRoomInformation.cshtml
@model CSharpMVC_BuildingAndConferenceRoomAppAssignment.ViewModels.EnterConferenceRoomInformationViewModel

@{
    ViewBag.Title = "EnterConferenceRoomInformationView";
}

<h2>New Conference Room Information</h2>

@using (Html.BeginForm("EnterConferenceRoomInformation", "ConferenceRoomInformation", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Please enter information on the conference room.</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomBuilding, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomBuilding, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomBuilding, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomPhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomPhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomPhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomIsAVCapable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.RoomIsAVCapable)
                    @Html.ValidationMessageFor(model => model.RoomIsAVCapable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomCapacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomCapacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" onclick="ClearMessage();" />
            </div>
        </div>

        <br />

        @{
            if (Model != null)
            {
                if (Model.EntrySuccessful)
                {
                    <h3 id="h3-message">@Model.Message</h3>         
                    Model.EntrySuccessful = false;
                }                
            }
        }
    </div>
}

<div>
    @Html.ActionLink("Main Menu", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        function ClearMessage() {
            const msg = document.getElementById('h3-message');
            msg.innerHTML = "";
        }
    </script>
}

CSharpMVC_BuildingAndConferenceRoomAppAssignment/Views/ConferenceRoomInformation/SaveConferenceRoomDetail.cshtml
@{
    ViewBag.Title = "SaveConferenceRoomDetail";
}

<h1>Success!</h1>

<h2>Conference Room details successfully saved!</h2>

<div>
    @Html.ActionLink("Return to Conference Room Entry Form", "EnterConferenceRoomInformation", "ConferenceRoomInformation") <br />
    @Html.ActionLink("Main Menu", "Index", "Home")
</div>

CSharpMVC_BuildingAndConferenceRoomAppAssignment/Views/ConferenceRoomInformation/ViewConferenceRoomInformation.cshtml
@model IEnumerable<CSharpMVC_BuildingAndConferenceRoomAppAssignment.ViewModels.ViewConferenceRoomInformationViewModel>

@{
    ViewBag.Title = "ViewConferenceRoomInformation";
}

<h2>Conference Room Information</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RoomId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomBuilding)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomPhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomIsAVCapable)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomCapacity)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RoomId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoomName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoomBuilding)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoomPhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoomIsAVCapable)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoomCapacity)
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Main Menu", "Index", "Home")
</div>